# Generated by Django 4.2.3 on 2023-07-03 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('car_brand', models.CharField(max_length=100, null=True)),
                ('car_model', models.CharField(max_length=100, null=True)),
                ('plate_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingFee',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingfee.car')),
            ],
        ),
    ]
